// <auto-generated />
namespace BlogMvcApp.DLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class QustionnaireLanguage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QustionnaireLanguage));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141547477_QustionnaireLanguage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
