// <auto-generated />
namespace BlogMvcApp.DLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UpUserToArticleFeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpUserToArticleFeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "202002201600267_UpUserToArticleFeedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
